"""Chapter Six: Summary, Conclusion and Recommendations."""
from __future__ import annotations


def build(c: dict) -> list:
    B = []
    add = B.append

    add(("chapter_heading", "CHAPTER SIX"))
    add(("chapter_subtitle", "SUMMARY, CONCLUSION AND RECOMMENDATIONS"))

    # ---------------------------------------------------------------- 6.1
    add(("heading2", "6.1", "Summary of the Project"))
    add(("body",
         "This study addressed the detection and mitigation of prompt injection in "
         "applications built on large language models. Chapter One established the "
         "problem: because such models process instructions and data through a single "
         "channel, they cannot reliably distinguish a developer's instructions from an "
         "attacker's, and the resulting vulnerability is ranked first in the OWASP Top 10 "
         "for Large Language Model Applications (OWASP, 2025). Chapter Two reviewed the "
         "attack and defence literature and identified three gaps: deployed detectors "
         "over-defend and yet the false-positive rate is rarely treated as a first-class "
         "metric; detectors are brittle under adaptive evasion and this brittleness is "
         "seldom measured systematically; and the detection of indirect injection, the "
         "form most relevant to retrieval-augmented enterprise systems, remains immature."))
    add(("body",
         "Chapter Three set out an experimental, design-science methodology, and Chapters "
         "Four and Five report its execution. A labelled corpus of "
         f"{c['n_total']} unique prompts was assembled from six public sources and two "
         "authored sets, keeping benign content, direct injection, jailbreak and indirect "
         "injection as distinct classes and applying four explicit controls against "
         "spurious-feature learning. Three classical detectors and two fine-tuned "
         "transformers were trained under a common protocol over three seeds and evaluated "
         "on identical partitions. A model-agnostic screening middleware was implemented "
         "in Flask, screening the user-prompt and retrieved-content channels separately "
         "and applying a configurable block, sanitise or escalate policy, and it was "
         "integrated with a purpose-built vulnerable chatbot so that it could be observed "
         "operating in a live request path."))

    # ---------------------------------------------------------------- 6.2
    add(("heading2", "6.2", "Conclusion"))
    add(("body", c["conclusion_1"]))
    add(("body", c["conclusion_2"]))

    # ---------------------------------------------------------------- 6.3
    add(("heading2", "6.3", "Limitations"))
    add(("body",
         "The findings of this study are bounded in seven respects, each of which is "
         "stated plainly because it conditions how far the results generalise."))
    add(("body",
         "The first is the substitution of data sources. Chapter Three names HackAPrompt "
         "as the primary source of direct-injection samples, and JailbreakBench and "
         "PromptBench as further sources. HackAPrompt is distributed under gated access "
         "requiring an authenticated account, and was not available for this work; the "
         "direct-injection class was rebuilt from the Gandalf corpus, the deepset "
         "prompt-injection set and the injection portion of an open safety-guard corpus, "
         "and the jailbreak class from an open jailbreak-classification corpus in place of "
         "JailbreakBench. The substitutes are comparable in kind but not identical in "
         "provenance, and results are therefore not directly comparable with published "
         "figures on HackAPrompt."))
    add(("body",
         f"The second is the size of the indirect class. BIPIA supplies a fixed and modest "
         f"number of attack strings, and after composition and deduplication the indirect "
         f"class contains {c['n_indirect']} samples against {c['n_direct']} direct "
         "injections. Every claim about indirect detection accordingly rests on a much "
         "narrower base than the corresponding claim about direct injection, and the "
         "indirect result should be read as indicative rather than settled."))
    add(("body", c["limitation_evasion"]))
    add(("body",
         "The fourth is that the adaptive-evasion set is synthetic in the sense that it "
         "was generated by transformation rather than harvested from attackers actually "
         "attempting to defeat this detector. Nine of the ten transformations are "
         "rule-based and therefore have a fixed and knowable form; only the paraphrase "
         "transformation is genuinely open-ended. A determined adversary with query access "
         "to the deployed detector could search for evasions the transformation set does "
         "not represent, and the reported degradation should be read as a lower bound on "
         "the damage such an adversary could do."))
    add(("body", c["limitation_lab"]))
    add(("body",
         "The sixth is that all measurements were taken on a single workstation, in a "
         "single session, with the services on the loopback interface. The latency figures "
         "in Section 5.2.5 therefore exclude network transit, contention from concurrent "
         "users, and the cost of horizontal scaling; they establish the order of magnitude "
         "of the screening overhead but not its behaviour under production load."))
    add(("body",
         "The seventh is the boundary set in Section 1.6. Only text-based attacks are "
         "considered. Multimodal injection through images or audio, injection through "
         "tool-calling and agentic action chains, and attacks that manipulate the model's "
         "training data are all outside the scope of this work, and nothing reported here "
         "should be taken as evidence about them."))

    # ---------------------------------------------------------------- 6.4
    add(("heading2", "6.4", "Professional Contributions"))
    add(("body",
         "The contributions of this project are chiefly practical, as befits a "
         "professional master's degree, and fall under three headings."))
    add(("body", c["contribution_practice"]))
    add(("body",
         "The second concerns implementation practice. The project delivers a working, "
         "documented and tested artefact rather than a description of one: a stateless "
         "screening service with an HTTP interface, a decision policy separated from both "
         "the transport and the detector and covered by unit tests, a configurable "
         "threshold surface that lets an operator move along the sensitivity–usability "
         "trade-off deliberately, and an append-only audit log of every decision and "
         "score. The separate treatment of the user-prompt and retrieved-content channels "
         "is a design position with practical consequences: retrieved content has no "
         "legitimate authority to issue instructions, so it can be screened more strictly "
         "at almost no cost in user experience, and the implementation makes that "
         "asymmetry explicit and configurable rather than incidental."))
    add(("body",
         "The third concerns the wider digital-transformation context. Organisations "
         "adopting language-model assistants — in Nigeria as elsewhere — are deploying "
         "them in front of customer data and internal knowledge bases at a pace that "
         "outstrips their assurance practice. This work offers such organisations a "
         "defensible position: a screening layer that can be placed in front of an "
         "existing assistant without modifying it, evidence about what that layer does and "
         "does not catch, and an explicit account of the usability cost of getting the "
         "configuration wrong. The demonstration that a naive keyword filter refuses a "
         "substantial fraction of legitimate help-desk traffic is, in particular, an "
         "argument that ought to be available to practitioners deciding whether a "
         "rule-based control is adequate."))

    # ---------------------------------------------------------------- 6.5
    add(("heading2", "6.5", "Recommendations for Future Work"))
    add(("body",
         "Six directions follow from the limitations above, ordered roughly by how "
         "directly they would strengthen the present findings."))
    add(("body",
         "The first is to repeat the evaluation with the full HackAPrompt corpus and with "
         "JailbreakBench and PromptBench as Chapter Three originally specified. The data "
         "loader is written so that these can be added without other change, and doing so "
         "would make the results directly comparable with the published literature."))
    add(("body",
         "The second is to enlarge the indirect-injection class substantially. This is the "
         "gap the literature identifies as least mature and it is the class on which this "
         "study has the least evidence. Composing attacks into a wider variety of "
         "retrieved containers, and drawing on retrieval corpora beyond BIPIA, would put "
         "indirect detection on the same evidential footing as direct detection."))
    add(("body",
         "The third is adversarial training against the evasion set. The transformations "
         "used here to measure robustness could equally be used to augment the training "
         "data, and the natural experiment is to measure how much of the degradation "
         "reported in Section 5.2.4 can be recovered without inflating the false-positive "
         "rate — since an unconstrained defence against obfuscation is precisely the sort "
         "of change likely to cause over-defence."))
    add(("body",
         "The fourth is to evaluate the middleware against an adaptive adversary with "
         "query access to the deployed detector, rather than against a fixed transformation "
         "set. This is the evaluation that would test the robustness claim most severely, "
         "and the literature reviewed in Chapter Two suggests it is where detection-based "
         "defences are most likely to fail."))
    add(("body",
         "The fifth is to extend screening beyond the two channels implemented here to "
         "tool-calling and agentic action chains, where an injected instruction can cause "
         "an action rather than merely a disclosure, and where the consequences of a "
         "missed detection are correspondingly greater."))
    add(("body",
         "The last recommendation is organisational rather than technical. The evidence in "
         "Section 5.2.6 is that the cost of a poorly configured defence is borne by "
         "ordinary users, silently, in the form of refused legitimate requests. Any "
         "organisation deploying such a control should therefore monitor its refusal rate "
         "on live traffic as a first-class operational metric, alongside its detection "
         "rate, and should treat an unexplained rise in refusals as an incident in its own "
         "right. A defence whose usability cost is never measured will be tuned by "
         "complaint rather than by evidence."))

    return B
